var PeriodicTable = [{
        proton: 1,
        neutron:0,
        Symbol: "H",
		name:"Hydrogen",
		type:"NONMETALS",
		block:"S",
        isotope: [2,3,1],
        boilingPoint: -252.9,
        Electronegativity: 2.20,
        Density: 0.09,
        // AtomicMass: 1.008,
        AtomicMass: 1.0079,
        IonizationEnergy: 1312.0,
        AtomicRadius: 0.25,
        AtomicRadius_InPicometers: 53,
        MeltingPoint: -259.1,
        ElementColor: "rgb(235,235,235)",
    }, {
        proton: 2,
        neutron: 2,
        Symbol: "He",
		name:"Helium",
		type:"NOBLE GASES",
		block:"S",
        isotope:[3,4],
        boilingPoint: -268.9,
        Electronegativity: null,
        Density: 0.18,
        // AtomicMass: 4.003,
        AtomicMass: 4.0026,
        IonizationEnergy: 2372,
        AtomicRadius: 0.31,
		AtomicRadius_InPicometers: 31,
        MeltingPoint: -272.2,
        ElementColor: "rgb(254,192,233)"
    }, {
        proton: 3,
        Symbol: "Li",
		name:"Lithium",
		type:"ALKALI METALS",
		block:"S",
        boilingPoint: 1347,
        Electronegativity: 0.98,
        Density: 0.54,
        AtomicMass: 6.9410,
        IonizationEnergy: 520.2,
        AtomicRadius: 1.45,
		AtomicRadius_InPicometers: 167,
        MeltingPoint: 180.5,
        ElementColor: "rgb(254,192,192)"
    }, {
        proton: 4,
        Symbol: "Be",
		name:"Beryllium",
		type:"ALKALINE EARTH METALS",
		block:"S",
        boilingPoint: 2970,
        Electronegativity: 1.57,
        Density: 1.85,
        AtomicMass: 9.0122,
        IonizationEnergy: 899.5,
        AtomicRadius: 1.05,
		AtomicRadius_InPicometers: 112,
        MeltingPoint: 1287,
        ElementColor: "rgb(254,192,151)"
    }, {
        proton: 5,
        Symbol: "B",
        name: "Boron",
		type:"METALLOIDS",
		block:"P",
        boilingPoint: 3927,
        Electronegativity: 2.04,
        Density: 2.46,
        AtomicMass: 10.8110,
        IonizationEnergy: 800.6,
        AtomicRadius: 0.85,
		AtomicRadius_InPicometers: 87,
        MeltingPoint: 2076,
        ElementColor: "rgb(254,171,233)"
    }, {
        proton: 6,
        neutron:6,
        Symbol: "C",
        name: "Carbon",
		type:"NONMETALS",
		block:"P",
        isotope: [11,14,9,10,15,16,17,13],
        boilingPoint: 4027,
        Electronegativity: 2.55,
        Density: 2.26,
        AtomicMass: 12.0107,
        IonizationEnergy: 1087,
        AtomicRadius: 0.70,
		AtomicRadius_InPicometers: 67,
        MeltingPoint: 3527,
        ElementColor: "rgb(138,138,138)"
    }, {
        proton: 7,
        neutron:7,
        Symbol: "N",
        name: "Nitrogen",
		type:"NONMETALS",
		block:"P",
      isotope: [13,14,15],
        boilingPoint: -195.8,
        Electronegativity: 3.04,
        Density: 1.25,
        AtomicMass: 14.0067,
        IonizationEnergy: 1402,
        AtomicRadius: 0.65,
		AtomicRadius_InPicometers: 56,
        MeltingPoint: -210.0,
        ElementColor: "rgb(51,84,189)"
    }, {
        proton: 8,
        Symbol: "O",
		name:"Oxygen",
		type:"NONMETALS",
		block:"P",
        isotope:[14,15,17,18],
        boilingPoint: -183.0,
        Electronegativity: 3.44,
        Density: 1.43,
        AtomicMass: 15.9994,
        IonizationEnergy: 1314,
        AtomicRadius: 0.60,
		AtomicRadius_InPicometers: 48,
        MeltingPoint: -218.8,
        ElementColor: "rgb(241,64,72)"
    }, {
        proton: 9,
        Symbol: "F",
		name:"Fluorine",
		type:"HALOGENS",
		block:"P",
        boilingPoint: -188.1,
        Electronegativity: 3.98,
        Density: 1.70,
        AtomicMass: 18.9984,
        IonizationEnergy: 1681,
        AtomicRadius: 0.50,
		AtomicRadius_InPicometers: 42,
        MeltingPoint: -219.7,
        // ElementColor: "rgb(254,151,192)"
        ElementColor: "rgb(133, 253, 100)"
    }, {
        proton: 10,
        Symbol: "Ne",
		name:"Neon",
		type:"NOBLE GASES",
		block:"P",
        boilingPoint: -246.0,
        Electronegativity: null,
        Density: 0.90,
        AtomicMass: 20.1797,
        IonizationEnergy: 2081,
        AtomicRadius: 0.38,
		AtomicRadius_InPicometers: 38,
        MeltingPoint: -248.6,
        ElementColor: "rgb(254,151,151)"
    }, {
        proton: 11,
        Symbol: "Na",
        name: "Sodium",
		type:"ALKALI METALS",
		block:"S",
        isotope: [24,21,22,25,26],
        boilingPoint: 882.9,
        Electronegativity: 0.93,
        Density: 0.97,
        AtomicMass: 22.9897,
        IonizationEnergy: 495.8,
        AtomicRadius: 1.80,
		AtomicRadius_InPicometers: 190,
        MeltingPoint: 97.79,
        // ElementColor: "rgb(233,254,233)"
        ElementColor: "rgb(154,126,184)"
    }, {
        proton: 12,
        Symbol: "Mg",
        name: "Magnesium",
		type:"ALKALINE EARTH METALS",
		block:"S",
        boilingPoint: 1090,
        Electronegativity: 1.31,
        Density: 1.74,
        AtomicMass: 24.31,// as ticket HGC-5744 (old value : 24.3050)
        IonizationEnergy: 737.7,
        AtomicRadius: 1.50,
		AtomicRadius_InPicometers: 145,
        MeltingPoint: 650.0,
        ElementColor: "rgb(243,264,202)"
    }, {
        proton: 13,
        Symbol: "Al",
		name:"Aluminum", // as ticket HGC-5745 (old value : Aluminium)
		type:"POOR METALS",
		block:"P",
        boilingPoint: 2470,
        Electronegativity: 1.61,
        Density: 2.70,
        AtomicMass: 26.9815,
        IonizationEnergy: 577.5,
        AtomicRadius: 1.25,
		AtomicRadius_InPicometers: 118,
        MeltingPoint: 660.3,
        ElementColor: "rgb(191,191,191)"
    }, {
        proton: 14,
        Symbol: "Si",
		name:"Silicon",
		type:"METALLOIDS",
		block:"P",
        boilingPoint: 3265,
        Electronegativity: 1.90,
        Density: 2.33,
        AtomicMass: 28.0855,
        IonizationEnergy: 786.5,
        AtomicRadius: 1.10,
		AtomicRadius_InPicometers: 111,
        MeltingPoint: 1414,
        ElementColor: "rgb(233,233,233)"
    }, {
        proton: 15,
        Symbol: "P",
		name:"Phosphorus",
		type:"NONMETALS",
		block:"P",
        boilingPoint: 277.0,
        Electronegativity: 2.19,
        Density: 1.82,
        AtomicMass: 30.9738,
        IonizationEnergy: 1012,
        AtomicRadius: 1.00,
		AtomicRadius_InPicometers: 98,
        MeltingPoint: 44.15,
        ElementColor: "rgb(233,220,182)"
    }, {
        proton: 16,
        Symbol: "S",
		name:"Sulfur",
		type:"NONMETALS",
		block:"P",
        boilingPoint: 444.6,
        Electronegativity: 2.58,
        Density: 1.96,
        AtomicMass: 32.0650,
        IonizationEnergy: 999.6,
        AtomicRadius: 1.00,
		AtomicRadius_InPicometers: 88,
        MeltingPoint: 95.30,
        ElementColor: "rgb(216,206,109)"
    }, {
        proton: 17,
        Symbol: "Cl",
		name:"Chlorine",
		type:"HALOGENS",
		block:"P",
        boilingPoint: -34.04,
        Electronegativity: 3.16,
        Density: 3.21,
        AtomicMass: 35.4530,
        IonizationEnergy: 1251,
        AtomicRadius: 1.00,
		AtomicRadius_InPicometers: 79,
        MeltingPoint: -101.5,
        ElementColor: "rgb(86,172,61)"
    }, {
        proton: 18,
        Symbol: "Ar",
		name:"Argon",
		type:"NOBLE GASES",
		block:"P",
        boilingPoint: -185.8,
        Electronegativity: null,
        Density: 1.78,
        AtomicMass: 39.9480,
        IonizationEnergy: 1521,
        AtomicRadius: 0.71,
		AtomicRadius_InPicometers: 71,
        MeltingPoint: -189.3,
        ElementColor: "rgb(233,212,192)"
    }, {
        proton: 19,
        Symbol: "K",
		name:"Potassium",
		type:"ALKALI METALS",
		block:"S",
        boilingPoint: 759.0,
        Electronegativity: 0.82,
        Density: 0.86,
        AtomicMass: 39.0983,
        IonizationEnergy: 418.8,
        AtomicRadius: 2.20,
		AtomicRadius_InPicometers: 243,
        MeltingPoint: 63.50,
        ElementColor: "rgb(233,212,151)"
    }, {
        proton: 20,
        Symbol: "Ca",
		name:"Calcium",
		type:"ALKALINE EARTH METALS",
		block:"S",
        boilingPoint: 1484,
        Electronegativity: 1.00,
        Density: 1.55,
        AtomicMass: 40.0780,
        IonizationEnergy: 589.8,
        AtomicRadius: 1.80,
		AtomicRadius_InPicometers: 194,
        MeltingPoint: 482.0,
        ElementColor: "rgb(184,159,184)"
    }, {
        proton: 21,
        Symbol: "Sc",
		name:"Scandium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 2836,
        Electronegativity: 1.36,
        Density: 2.99,
        AtomicMass: 44.9559,
        IonizationEnergy: 633.1,
        AtomicRadius: 1.60,
		AtomicRadius_InPicometers: 184,
        MeltingPoint: 1541,
        ElementColor: "rgb(233,192,192)"
    }, {
        proton: 22,
        Symbol: "Ti",
		name:"Titanium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 3287,
        Electronegativity: 1.54,
        Density: 4.51,
        AtomicMass: 47.8670,
        IonizationEnergy: 658.8,
        AtomicRadius: 1.40,
		AtomicRadius_InPicometers: 176,
        MeltingPoint: 1668,
        ElementColor: "rgb(233,192,151)"
    }, {
        proton: 23,
        Symbol: "V",
		name:"Vanadium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 3407,
        Electronegativity: 1.36,
        Density: 6.11,
        AtomicMass: 50.9415,
        IonizationEnergy: 650.9,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 171,
        MeltingPoint: 1910,
        ElementColor: "rgb(233,171,233)"
    }, {
        proton: 24,
        Symbol: "Cr",
        name: "Chromium",
		type:"TRANSITION METALS",
		block:"D",
        isotope: [50,48,49,51,55,56],
        boilingPoint: 2482,
        Electronegativity: 1.66,
        Density: 7.14,
        AtomicMass: 51.9961,
        IonizationEnergy: 652.9,
        AtomicRadius: 1.40,
		AtomicRadius_InPicometers: 166,
        MeltingPoint: 1907,
        ElementColor: "rgb(233,171,192)"
    }, {
        proton: 25,
        Symbol: "Mn",
        name: "Manganese",
		type:"TRANSITION METALS",
		block:"D",
        isotope: [50,51,52,53,54,56,57],
        boilingPoint: 2061,
        Electronegativity: 1.55,
        Density: 7.47,
        AtomicMass: 54.9380,
        IonizationEnergy: 717.3,
        AtomicRadius: 1.40,
		AtomicRadius_InPicometers: 161,
        MeltingPoint: 1246,
        ElementColor: "rgb(233,171,151)"
    }, {
        proton: 26,
        Symbol: "Fe",
		name:"Iron",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 2861,
        Electronegativity: 1.83,
        Density: 7.87,
        AtomicMass: 55.8450,
        IonizationEnergy: 762.5,
        AtomicRadius: 1.40,
		AtomicRadius_InPicometers: 156,
        MeltingPoint: 1538,
        ElementColor: "rgb(233,151,233)"
    }, {
        proton: 27,
        Symbol: "Co",
		name:"Cobalt",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 2927,
        Electronegativity: 1.88,
        Density: 8.90,
        AtomicMass: 58.9332,
        IonizationEnergy: 760.4,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 152,
        MeltingPoint: 1495,
        ElementColor: "rgb(233,151,192)"
    }, {
        proton: 28,
        Symbol: "Ni",
		name:"Nickel",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 2730,
        Electronegativity: 1.91,
        Density: 8.91,
        AtomicMass: 58.6934,
        IonizationEnergy: 737.1,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 149,
        MeltingPoint: 1455,
        ElementColor: "rgb(233,151,151)"
    }, {
        proton: 29,
        Symbol: "Cu",
		name:"Copper",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 2562,
        Electronegativity: 1.90,
        Density: 8.92,
        AtomicMass: 63.5460,
        IonizationEnergy: 745.5,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 145,
        MeltingPoint: 1085,
        ElementColor: "rgb(212,254,233)"
    }, {
        proton: 30,
        Symbol: "Zn",
		name:"Zinc",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 907.0,
        Electronegativity: 1.65,
        Density: 7.14,
        AtomicMass: 65.3900,
        IonizationEnergy: 906.4,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 142,
        MeltingPoint: 419.5,
        ElementColor: "rgb(212,254,192)"
    }, {
        proton: 31,
        Symbol: "Ga",
		name:"Gallium",
		type:"POOR METALS",
		block:"P",
        boilingPoint: 2400,
        Electronegativity: 1.81,
        Density: 5.90,
        AtomicMass: 69.7230,
        IonizationEnergy: 578.8,
        AtomicRadius: 1.30,
		AtomicRadius_InPicometers: 136,
        MeltingPoint: 29.76,
        ElementColor: "rgb(212,254,151)"
    }, {
        proton: 32,
        Symbol: "Ge",
		name:"Germanium",
		type:"METALLOIDS",
		block:"P",
        boilingPoint: 2833,
        Electronegativity: 2.01,
        Density: 5.32,
        AtomicMass: 72.6400,
        IonizationEnergy: 762.2,
        AtomicRadius: 1.25,
		AtomicRadius_InPicometers: 125,
        MeltingPoint: 938.3,
        ElementColor: "rgb(212,233,233)"
    }, {
        proton: 33,
        Symbol: "As",
		name:"Arsenic",
		type:"METALLOIDS",
		block:"P",
        boilingPoint: 614.0,
        Electronegativity: 2.18,
        Density: 5.73,
        AtomicMass: 74.9216,
        IonizationEnergy: 944.5,
        AtomicRadius: 1.15,
		AtomicRadius_InPicometers: 114,
        MeltingPoint: 817.0,
        ElementColor: "rgb(212,233,192)"
    }, {
        proton: 34,
        Symbol: "Se",
		name:"Selenium",
		type:"NONMETALS",
		block:"P",
        boilingPoint: 685.0,
        Electronegativity: 2.55,
        Density: 4.82,
        AtomicMass: 78.9600,
        IonizationEnergy: 941.0,
        AtomicRadius: 1.15,
		AtomicRadius_InPicometers: 103,
        MeltingPoint: 221.0,
        ElementColor: "rgb(212,233,151)"
    }, {
        proton: 35,
        Symbol: "Br",
		name:"Bromine",
		type:"HALOGENS",
		block:"P",
        boilingPoint: 58.80,
        Electronegativity: 2.96,
        Density: 3.12,
        AtomicMass: 79.9040,
        IonizationEnergy: 1140,
        AtomicRadius: 1.15,
		AtomicRadius_InPicometers: 94,
        MeltingPoint: -7.300,
        ElementColor: "rgb(167,84,66)"
    }, {
        proton: 36,
        neutron:48,
        Symbol: "Kr",
		name:"Krypton",
		type:"NOBLE GASES",
		block:"P",
        isotope:[90,92],
        boilingPoint: -153.4,
        Electronegativity: 3.00,
        Density: 3.75,
        AtomicMass: 83.8000,
        IonizationEnergy: 1351,
        AtomicRadius: 0.88,
		AtomicRadius_InPicometers: 88,
        MeltingPoint: -157.4,
        ElementColor: "rgb(212,212,192)"
    }, {
        proton: 37,
        Symbol: "Rb",
		name:"Rubidium",
		type:"ALKALI METALS",
		block:"S",
        boilingPoint: 688.0,
        Electronegativity: 0.82,
        Density: 1.53,
        AtomicMass: 85.4678,
        IonizationEnergy: 403.0,
        AtomicRadius: 2.35,
		AtomicRadius_InPicometers: 265,
        MeltingPoint: 39.30,
        ElementColor: "rgb(212,212,151)"
    }, {
        proton: 38,
        Symbol: "Sr",
		name:"Strontium",
		type:"ALKALINE EARTH METALS",
		block:"S",
        boilingPoint: 1382,
        Electronegativity: 0.95,
        Density: 2.63,
        AtomicMass: 87.6200,
        IonizationEnergy: 549.5,
        AtomicRadius: 2.00,
		AtomicRadius_InPicometers: 219,
        MeltingPoint: 777.0,
        ElementColor: "rgb(212,192,233)"
    }, {
        proton: 39,
        Symbol: "Y",
		name:"Yttrium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 2930,
        Electronegativity: 1.22,
        Density: 4.47,
        AtomicMass: 88.9056,
        IonizationEnergy: 599.9,
        AtomicRadius: 1.80,
		AtomicRadius_InPicometers: 212,
        MeltingPoint: 1526,
        ElementColor: "rgb(212,192,192)"
    }, {
        proton: 40,
        neutron:51,
        Symbol: "Zr",
		name:"Zirconium",
		type:"TRANSITION METALS",
		block:"D",
        isotope:[92,93,94,95,96],
        boilingPoint: 4377,
        Electronegativity: 1.33,
        Density: 6.51,
        AtomicMass: 91.2240,
        IonizationEnergy: 640.1,
        AtomicRadius: 1.55,
		AtomicRadius_InPicometers: 206,
        MeltingPoint: 1855,
        ElementColor: "rgb(212,192,151)"
    }, {
        proton: 41,
        Symbol: "Nb",
		name:"Niobium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 4744,
        Electronegativity: 1.60,
        Density: 8.57,
        AtomicMass: 92.9064,
        IonizationEnergy: 652.1,
        AtomicRadius: 1.45,
		AtomicRadius_InPicometers: 198,
        MeltingPoint: 2477,
        ElementColor: "rgb(212,171,233)"
    }, {
        proton: 42,
        Symbol: "Mo",
		name:"Molybdenum",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 4639,
        Electronegativity: 2.16,
        Density: 10.28,
        AtomicMass: 95.9400,
        IonizationEnergy: 684.3,
        AtomicRadius: 1.45,
		AtomicRadius_InPicometers: 190,
        MeltingPoint: 2623,
        ElementColor: "rgb(212,171,192)"
    }, {
        proton: 43,
        Symbol: "Tc",
		name:"Technetium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 4265,
        Electronegativity: 1.90,
        Density: 11.49,
        AtomicMass: 98,
        IonizationEnergy: 702.4,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 183,
        MeltingPoint: 2157,
        ElementColor: "rgb(212,171,151)"
    }, {
        proton: 44,
        Symbol: "Ru",
		name:"Ruthenium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 4150,
        Electronegativity: 2.20,
        Density: 12.37,
        AtomicMass: 101.0700,
        IonizationEnergy: 710.2,
        AtomicRadius: 1.30,
		AtomicRadius_InPicometers: 178,
        MeltingPoint: 2334,
        ElementColor: "rgb(212,151,233)"
    }, {
        proton: 45,
        Symbol: "Rh",
		name:"Rhodium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 3695,
        Electronegativity: 2.28,
        Density: 12.45,
        AtomicMass: 102.9055,
        IonizationEnergy: 719.7,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 173,
        MeltingPoint: 1964,
        ElementColor: "rgb(212,151,192)"
    }, {
        proton: 46,
        Symbol: "Pd",
		name:"Palladium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 2963,
        Electronegativity: 2.20,
        Density: 12.02,
        AtomicMass: 106.4200,
        IonizationEnergy: 804.4,
        AtomicRadius: 1.40,
		AtomicRadius_InPicometers: 169,
        MeltingPoint: 1555,
        ElementColor: "rgb(212,151,151)"
    }, {
        proton: 47,
        Symbol: "Ag",
		name:"Silver",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 2210,
        Electronegativity: 1.93,
        Density: 10.49,
        AtomicMass: 107.8682,
        IonizationEnergy: 731.0,
        AtomicRadius: 1.60,
		AtomicRadius_InPicometers: 165,
        MeltingPoint: 961.8,
        ElementColor: "rgb(192,254,233)"
    }, {
        proton: 48,
        Symbol: "Cd",
		name:"Cadmium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 767.0,
        Electronegativity: 1.69,
        Density: 8.65,
        AtomicMass: 112.4110,
        IonizationEnergy: 867.8,
        AtomicRadius: 1.55,
		AtomicRadius_InPicometers: 161,// as ticket HGC-5750 (old value : 155)
        MeltingPoint: 321.1,
        ElementColor: "rgb(192,254,192)"
    }, {
        proton: 49,
        Symbol: "In",
		name:"Indium",
		type:"POOR METALS",
		block:"P",
        boilingPoint: 2072,
        Electronegativity: 1.78,
        Density: 7.31,
        AtomicMass: 114.82,// as ticket HGC-5746 (old value : 144.8180)
        IonizationEnergy: 558.3,
        AtomicRadius: 1.55,
		AtomicRadius_InPicometers: 156,
        MeltingPoint: 156.6,
        ElementColor: "rgb(192,254,151)"
    }, {
        proton: 50,
        Symbol: "Sn",
		name:"Tin",
		type:"POOR METALS",
		block:"P",
        boilingPoint: 2602,
        Electronegativity: 1.96,
        Density: 7.31,
        AtomicMass: 118.7100,
        IonizationEnergy: 708.6,
        AtomicRadius: 1.45,
		AtomicRadius_InPicometers: 145,
        MeltingPoint: 231.9,
        ElementColor: "rgb(192,233,233)"
    }, {
        proton: 51,
        Symbol: "Sb",
		name:"Antimony",
		type:"METALLOIDS",
		block:"P",
        boilingPoint: 1635,
        Electronegativity: 2.05,
        Density: 6.69,
        AtomicMass: 121.7600,
        IonizationEnergy: 830.6,
        AtomicRadius: 1.45,
		AtomicRadius_InPicometers: 133,
        MeltingPoint: 630.6,
        ElementColor: "rgb(192,233,192)"
    }, {
        proton: 52,
        neutron:76,
        Symbol: "Te",
		name:"Tellurium",
		type:"METALLOIDS",
		block:"P",
        isotope:[128,130,139],
        boilingPoint: 988.0,
        Electronegativity: 2.10,
        Density: 6.24,
        AtomicMass: 127.6000,
        IonizationEnergy: 869.3,
        AtomicRadius: 1.40,
		AtomicRadius_InPicometers: 123,
        MeltingPoint: 449.5,
        ElementColor: "rgb(192,233,151)"
    }, {
        proton: 53,
        Symbol: "I",
        name: "Iodine",
		type:"HALOGENS",
		block:"P",
        isotope: [118,131,120,121,122,123,124,125,126,128,129,130,132,133,134,135],
        boilingPoint: 184.3,
        Electronegativity: 2.66,
        Density: 4.94,
        AtomicMass: 126.9045,
        IonizationEnergy: 1008,
        AtomicRadius: 1.40,
		AtomicRadius_InPicometers: 115,
        MeltingPoint: 113.7,
        ElementColor: "rgb(108,77,137)"
    }, {
        proton: 54,
        Symbol: "Xe",
        name: "Xenon",
		type:"NOBLE GASES",
		block:"P",
        isotope: [118,122,123,125,127,133,135],
        boilingPoint: -108.1,
        Electronegativity: 2.60,
        Density: 5.90,
        AtomicMass: 131.2930,
        IonizationEnergy: 1170,
        AtomicRadius: 1.08,
		AtomicRadius_InPicometers: 108,
        MeltingPoint: -111.8,
        ElementColor: "rgb(192,212,192)"
    }, {
        proton: 55,
        Symbol: "Cs",
		name:"Cesium",
		type:"ALKALI METALS",
		block:"S",
        boilingPoint: 671.0,
        Electronegativity: 0.79,
        Density: 1.88,
        AtomicMass: 132.9055,
        IonizationEnergy: 375.7,
        AtomicRadius: 2.60,
		AtomicRadius_InPicometers: 298,
        MeltingPoint: 28.50,
        ElementColor: "rgb(192,212,151)"
    }, {
        proton: 56,
        neutron:81,
        Symbol: "Ba",
		name:"Barium",
		type:"ALKALINE EARTH METALS",
		block:"S",
        isotope:[141,144],
        boilingPoint: 1640,
        Electronegativity: 0.89,
        Density: 3.51,
        AtomicMass: 137.3270,
        IonizationEnergy: 502.9,
        AtomicRadius: 2.15,
		AtomicRadius_InPicometers: 253,
        MeltingPoint: 727.0,
        ElementColor: "rgb(192,192,233)"
    }, {
        proton: 57,
        Symbol: "La",
		name:"Lanthanum",
		type:"TRANSITION METALS",
		block:"F",
        boilingPoint: 3464,
        Electronegativity: 1.10,
        Density: 6.15,
        AtomicMass: 138.9055,
        IonizationEnergy: 538.1,
        AtomicRadius: 1.95,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 920.0,
        ElementColor: "rgb(192,192,192)"
    }, {
        proton: 58,
        Symbol: "Ce",
		name:"Cerium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 3443,
        Electronegativity: 1.12,
        Density: 6.69,
        AtomicMass: 140.1160,
        IonizationEnergy: 534.4,
        AtomicRadius: 1.85,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 795.0,
        ElementColor: "rgb(192,192,151)"
    }, {
        proton: 59,
        Symbol: "Pr",
        name: "Praseodymium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 3130,
        Electronegativity: 1.13,
        Density: 6.40,
        AtomicMass: 140.9077,
        IonizationEnergy: 528.1,
        AtomicRadius: 1.85,
		AtomicRadius_InPicometers: 247,
        MeltingPoint: 935.0,
        ElementColor: "rgb(192,171,233)"
    }, {
        proton: 60,
        Symbol: "Nd",
        name: "Neodymium",
		type:"LANTHANIDES",
		block:"F",
        isotope: [141,138,139,140,147,149],
        boilingPoint: 3074,
        Electronegativity: 1.14,
        Density: 7.01,
        AtomicMass: 144.2400,
        IonizationEnergy: 533.1,
        AtomicRadius: 1.85,
		AtomicRadius_InPicometers: 206,
        MeltingPoint: 1024,
        ElementColor: "rgb(192,171,192)"
    }, {
        proton: 61,
        Symbol: "Pm",
		name:"Promethium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 3000,
        Electronegativity: 1.13,
        Density: 7.26,
        AtomicMass: 145.000,
        IonizationEnergy: 538.6,
        AtomicRadius: 1.85,
		AtomicRadius_InPicometers: 205,
        MeltingPoint: 1042,
        ElementColor: "rgb(192,171,151)"
    }, {
        proton: 62,
        Symbol: "Sm",
		name:"Samarium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 1900,
        Electronegativity: 1.17,
        Density: 7.35,
        AtomicMass: 150.3600,
        IonizationEnergy: 544.5,
        AtomicRadius: 1.85,
		AtomicRadius_InPicometers: 238,
        MeltingPoint: 1072,
        ElementColor: "rgb(192,151,233)"
    }, {
        proton: 63,
        Symbol: "Eu",
		name:"Europium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 1529,
        Electronegativity: 1.20,
        Density: 5.24,
        AtomicMass: 151.9640,
        IonizationEnergy: 547.1,
        AtomicRadius: 1.85,
		AtomicRadius_InPicometers: 231,
        MeltingPoint: 826.0,
        ElementColor: "rgb(192,151,192)"
    }, {
        proton: 64,
        Symbol: "Gd",
		name:"Gadolinium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 3000,
        Electronegativity: 1.20,
        Density: 7.90,
        AtomicMass: 157.2500,
        IonizationEnergy: 593.4,
        AtomicRadius: 1.80,
		AtomicRadius_InPicometers: 233,
        MeltingPoint: 1312,
        ElementColor: "rgb(192,151,151)"
    }, {
        proton: 65,
        Symbol: "Tb",
		name:"Terbium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 3123,
        Electronegativity: 1.10,
        Density: 8.22,
        AtomicMass: 158.9253,
        IonizationEnergy: 565.8,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: 225,
        MeltingPoint: 1356,
        ElementColor: "rgb(171,254,233)"
    }, {
        proton: 66,
        Symbol: "Dy",
		name:"Dysprosium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 2567,
        Electronegativity: 1.22,
        Density: 8.55,
        AtomicMass: 162.5000,
        IonizationEnergy: 573.0,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: 228,
        MeltingPoint: 1407,
        ElementColor: "rgb(171,254,192)"
    }, {
        proton: 67,
        Symbol: "Ho",
		name:"Holmium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 2600,
        Electronegativity: 1.23,
        Density: 8.79,
        AtomicMass: 164.9303,
        IonizationEnergy: 581.0,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: 226,
        MeltingPoint: 1461,
        ElementColor: "rgb(171,254,151)"
    }, {
        proton: 68,
        Symbol: "Er",
		name:"Erbium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 2868,
        Electronegativity: 1.24,
        Density: 9.07,
        AtomicMass: 167.2590,
        IonizationEnergy: 589.3,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: 226,
        MeltingPoint: 1529,
        ElementColor: "rgb(171,233,233)"
    }, {
        proton: 69,
        Symbol: "Tm",
		name:"Thulium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 1730,
        Electronegativity: 1.25,
        Density: 9.32,
        AtomicMass: 168.9342,
        IonizationEnergy: 596.7,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: 222,
        MeltingPoint: 1545,
        ElementColor: "rgb(171,233,192)"
    }, {
        proton: 70,
        Symbol: "Yb",
		name:"Ytterbium",
		type:"LANTHANIDES",
		block:"F",
        boilingPoint: 1196,
        Electronegativity: 1.10,
        Density: 6.57,
        AtomicMass: 173.0400,
        IonizationEnergy: 603.4,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: 222,
        MeltingPoint: 824.0,
        ElementColor: "rgb(171,233,151)"
    }, {
        proton: 71,
        Symbol: "Lu",
		name:"Lutetium",
		type:"LANTHANIDES",
		block:"D",
        boilingPoint: 3402,
        Electronegativity: 1.27,
        Density: 9.84,
        AtomicMass: 174.9670,
        IonizationEnergy: 523.5,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: 217,
        MeltingPoint: 1652,
        ElementColor: "rgb(171,212,233)"
    }, {
        proton: 72,
        Symbol: "Hf",
		name:"Hafnium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 4603,
        Electronegativity: 1.30,
        Density: 13.31,
        AtomicMass: 178.4900,
        IonizationEnergy: 658.5,
        AtomicRadius: 1.55,
		AtomicRadius_InPicometers: 208,
        MeltingPoint: 2233,
        ElementColor: "rgb(171,212,192)"
    }, {
        proton: 73,
        Symbol: "Ta",
        name: "Tantalum",
		type:"TRANSITION METALS",
		block:"D",
        isotope: [177,178,179,180,182,183],
        boilingPoint: 5458,
        Electronegativity: 1.50,
        Density: 16.65,
        AtomicMass: 180.9479,
        IonizationEnergy: 728.4,
        AtomicRadius: 1.45,
		AtomicRadius_InPicometers: 200,
        MeltingPoint: 3017,
        ElementColor: "rgb(159,190,143)"
    }, {
        proton: 74,
        Symbol: "W",
        name: "Tungsten",
		type:"TRANSITION METALS",
		block:"D",
        isotope: [179,178,181,185,187,188],
        boilingPoint: 5930,
        Electronegativity: 2.36,
        Density: 19.25,
        AtomicMass: 183.8400,
        IonizationEnergy: 758.8,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 193,
        MeltingPoint: 3422,
        ElementColor: "rgb(171,192,233)"
    }, {
        proton: 75,
        Symbol: "Re",
		name:"Rhenium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 5596,
        Electronegativity: 1.90,
        Density: 21.02,
        AtomicMass: 186.2070,
        IonizationEnergy: 755.8,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 188,
        MeltingPoint: 3186,
        ElementColor: "rgb(171,192,192)"
    }, {
        proton: 76,
        Symbol: "Os",
		name:"Osmium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 5012,
        Electronegativity: 2.20,
        Density: 22.61,
        AtomicMass: 190.2300,
        IonizationEnergy: 814.2,
        AtomicRadius: 1.30,
		AtomicRadius_InPicometers: 185,
        MeltingPoint: 3033,
        ElementColor: "rgb(171,192,151)"
    }, {
        proton: 77,
        Symbol: "Ir",
		name:"Iridium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 4130,
        Electronegativity: 2.20,
        Density: 22.65,
        AtomicMass: 192.2170,
        IonizationEnergy: 865.2,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 180,
        MeltingPoint: 2446,
        ElementColor: "rgb(171,171,233)"
    }, {
        proton: 78,
        Symbol: "Pt",
        name: "Platinum",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 3825,
        Electronegativity: 2.28,
        Density: 21.09,
        AtomicMass: 195.0780,
        IonizationEnergy: 864.4,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 177,
        MeltingPoint: 1768,
        ElementColor: "rgb(171,171,192)"
    }, {
        proton: 79,
        Symbol: "Au",
        name: "Gold",
		type:"TRANSITION METALS",
		block:"D",
        isotope: [195,194,196,198,199],
        boilingPoint: 2970,
        Electronegativity: 2.54,
        Density: 19.32,
        AtomicMass: 196.9665,
        IonizationEnergy: 890.1,
        AtomicRadius: 1.35,
		AtomicRadius_InPicometers: 174,
        MeltingPoint: 1064,
        ElementColor: "rgb(171,171,151)"
    }, {
        proton: 80,
        Symbol: "Hg",
		name:"Mercury",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: 356.7,
        Electronegativity: 2.00,
        Density: 13.53,
        AtomicMass: 200.5900,
        IonizationEnergy: 1007,
        AtomicRadius: 1.50,
		AtomicRadius_InPicometers: 171,
        MeltingPoint: -38.83,
        ElementColor: "rgb(171,151,233)"
    }, {
        proton: 81,
        Symbol: "Tl",
		name:"Thallium",
		type:"POOR METALS",
		block:"P",
        boilingPoint: 1473,
        Electronegativity: 1.62,
        Density: 11.85,
        AtomicMass: 204.3833,
        IonizationEnergy: 589.4,
        AtomicRadius: 1.90,
		AtomicRadius_InPicometers: 156,
        MeltingPoint: 304.0,
        ElementColor: "rgb(171,151,192)"
    }, {
        proton: 82,
        Symbol: "Pb",
        name: "Lead",
		type:"POOR METALS",
		block:"P",
        isotope: [200,201,202,203,205,208,210,211,212],
        boilingPoint: 1749,
        Electronegativity: 2.33,
        Density: 11.34,
        AtomicMass: 207.2000,
        IonizationEnergy: 715.6,
        AtomicRadius: 1.80,
		AtomicRadius_InPicometers: 154,
        MeltingPoint: 327.5,
        ElementColor: "rgb(171,151,151)"
    }, {
        proton: 83,
        Symbol: "Bi",
		name:"Bismuth",
		type:"POOR METALS",
		block:"P",
        boilingPoint: 1564,
        Electronegativity: 2.02,
        Density: 9.78,
        AtomicMass: 208.9804,
        IonizationEnergy: 703.0,
        AtomicRadius: 1.60,
		AtomicRadius_InPicometers: 143,
        MeltingPoint: 271.5,
        ElementColor: "rgb(151,254,233)"
    }, {
        proton: 84,
        Symbol: "Po",
        name: "Polonium",
		type:"METALLOIDS",
		block:"P",
        isotope: [212,206,207,208,209,210],
        boilingPoint: 962.0,
        Electronegativity: 2.00,
        Density: 9.20,
        AtomicMass: 209,
        IonizationEnergy: 812.1,
        AtomicRadius: 1.90,
		AtomicRadius_InPicometers: 135,
        MeltingPoint: 254.0,
        ElementColor: "rgb(151,254,192)"
    }, {
        proton: 85,
        Symbol: "At",
		name:"Astatine",
		type:"HALOGENS",
		block:"P",
        boilingPoint: 337.0,
        Electronegativity: 2.20,
        Density: null,
        AtomicMass: 210,
        IonizationEnergy: 930.1,
        AtomicRadius: null,
		AtomicRadius_InPicometers: 127,
        MeltingPoint: 302.0,
        ElementColor: "rgb(151,254,151)"
    }, {
        proton: 86,
        Symbol: "Rn",
        name: "Radon",
		type:"NOBLE GASES",
		block:"P",
        boilingPoint: -61.70,
        Electronegativity: null,
        Density: 9.73,
        AtomicMass: 222,
        IonizationEnergy: 1037,
        AtomicRadius: 1.20,
		AtomicRadius_InPicometers: 120,
        MeltingPoint: -71.00,
        ElementColor: "rgb(151,233,233)"
    }, {
        proton: 87,
        Symbol: "Fr",
		name:"Francium",
		type:"ALKALI METALS",
		block:"S",
        boilingPoint: 677.0,
        Electronegativity: 0.70,
        Density: 1.87,
        AtomicMass: 223,
        IonizationEnergy: 393.0,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 27.00,
        ElementColor: "rgb(151,233,192)"
    }, {
        proton: 88,
        Symbol: "Ra",
        name: "Radium",
		type:"ALKALINE EARTH METALS",
		block:"S",
        isotope: [226,223,224,225,227,228],
        boilingPoint: 1737,
        Electronegativity: 0.90,
        Density: 5.50,
        AtomicMass: 226,
        IonizationEnergy: 509.3,
        AtomicRadius: 2.15,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 696.0,
        ElementColor: "rgb(151,233,151)"
    }, {
        proton: 89,
        Symbol: "Ac",
		name:"Actinium",
		type:"TRANSITION METALS",
		block:"F",
        boilingPoint: 3198,
        Electronegativity: 1.10,
        Density: 10.07,
        AtomicMass: 227,
        IonizationEnergy: 498.8,
        AtomicRadius: 1.95,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 1050,
        ElementColor: "rgb(151,212,233)"
    }, {
        proton: 90,
        Symbol: "Th",
        name: "Thorium",
		type:"ACTINIDES",
		block:"F",
        isotope: [227,228,229,230,231,232,233,234],
        boilingPoint: 4788,
        Electronegativity: 1.30,
        Density: 11.72,
        AtomicMass: 232.0381,
        IonizationEnergy: 608.5,
        AtomicRadius: 1.80,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 1755,
        ElementColor: "rgb(151,212,192)"
    }, {
        proton: 91,
        Symbol: "Pa",
		name:"Protactinium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: 4027,
        Electronegativity: 1.50,
        Density: 15.37,
        AtomicMass: 231.0359,
        IonizationEnergy: 568.3,
        AtomicRadius: 1.80,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 1568,
        ElementColor: "rgb(151,212,151)"
    }, {
        proton: 92,
        neutron:146,
        Symbol: "U",
        name: "Uranium",
		type:"ACTINIDES",
		block:"F",
        isotope: [238,230,231,232,233,234,235,236,237],
        boilingPoint: 4131,
        Electronegativity: 1.38,
        Density: 19.10,
        AtomicMass: 238.0289,
        IonizationEnergy: 597.6,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 1135,
        ElementColor: "rgb(151,192,233)"
    }, {
        proton: 93,
        Symbol: "Np",
		name:"Neptunium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: 4000,
        Electronegativity: 1.36,
        Density: 20.20,
        AtomicMass: 237,
        IonizationEnergy: 604.5,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 644.0,
        ElementColor: "rgb(151,192,192)"
    }, {
        proton: 94,
        Symbol: "Pu",
		name:"Plutonium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: 3228,
        Electronegativity: 1.28,
        Density: 19.81,
        AtomicMass: 244,
        IonizationEnergy: 581.4,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 639.4,
        ElementColor: "rgb(151,192,151)"
    }, {
        proton: 95,
        Symbol: "Am",
		name:"Americium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: 2607,
        Electronegativity: 1.13,
        Density: 12.00,
        AtomicMass: 243,
        IonizationEnergy: 576.4,
        AtomicRadius: 1.75,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 1176,
        ElementColor: "rgb(151,171,233)"
    }, {
        proton: 96,
        Symbol: "Cm",
		name:"Curium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: 3110,
        Electronegativity: 1.28,
        Density: 13.51,
        AtomicMass: 247,
        IonizationEnergy: 578.1,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 1340,
        ElementColor: "rgb(151,171,192)"
    }, {
        proton: 97,
        Symbol: "Bk",
		name:"Berkelium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: null,
        Electronegativity: 1.30,
        Density: 13.25,
        AtomicMass: 247,
        IonizationEnergy: 598.0,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 986.0,
        ElementColor: "rgb(151,171,151)"
    }, {
        proton: 98,
        Symbol: "Cf",
		name:"Californium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: null,
        Electronegativity: 1.30,
        Density: 15.10,
        AtomicMass: 251,
        IonizationEnergy: 606.1,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 900.0,
        ElementColor: "rgb(151,151,233)"
    }, {
        proton: 99,
        Symbol: "Es",
		name:"Einsteinium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: null,
        Electronegativity: 1.30,
        Density: 8.84,
        AtomicMass: 252,
        IonizationEnergy: 619.4,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 860.0,
        ElementColor: "rgb(151,151,192)"
    }, {
        proton: 100,
        Symbol: "Fm",
		name:"Fermium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: null,
        Electronegativity: 1.30,
        Density: null,
        AtomicMass: 257,
        IonizationEnergy: 627.2,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 1527,
        ElementColor: "rgb(247,151,151)"
    }, {
        proton: 101,
        Symbol: "Md",
		name:"Mendelevium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: null,
        Electronegativity: 1.30,
        Density: null,
        AtomicMass: 258,
        IonizationEnergy: 634.9,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 827.0,
        ElementColor: "rgb(226,151,151)"
    }, {
        proton: 102,
        Symbol: "No",
		name:"Nobelium",
		type:"ACTINIDES",
		block:"F",
        boilingPoint: null,
        Electronegativity: 1.30,
        Density: null,
        AtomicMass: 259,
        IonizationEnergy: 641.6,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 827.0,
        ElementColor: "rgb(206,151,151)"
    }, {
        proton: 103,
        Symbol: "Lr",
		name:"Lawrencium",
		type:"ACTINIDES",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 262,
        IonizationEnergy: 472.8,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: 1627,
        ElementColor: "rgb(185,151,151)"
    }, {
        proton: 104,
        Symbol: "Rf",
		name:"Rutherfordium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 261,
        IonizationEnergy: 578.9,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(165,151,151)"
    },

    {
        proton: 105,
        Symbol: "Db",
		name:"Dubnium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 262,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 106,
        Symbol: "Sg",
		name:"Seaborgium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 266,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 107,
        Symbol: "Bh",
		name:"Bohrium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 264,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 108,
        Symbol: "Hs",
		name:"Hassium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 277,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 109,
        Symbol: "Mt",
		name:"Meitnerium",
		type:"TRANSITION METALS",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 268,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 110,
        Symbol: "Ds",
		name:"darmstadtium",
		type:"undefined",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 281,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 111,
        Symbol: "Rg",
		name:"roentgenium",
		type:"undefined",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 280,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 112,
        Symbol: "Cn",
		name:"copernicum",
		type:"undefined",
		block:"D",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 285,
        IonizationEnergy: null,
        AtomicRadius: null,
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 113,
        Symbol: "Nh",
		name:"Nihonium",
		type:"undefined",
		block:"P",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 284,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 114,
        Symbol: "Fl",
		name:"flerovium",
		type:"undefined",
		block:"P",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 289,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 115,
        Symbol: "Mc",
		name:"Moscovium",
		type:"undefined",
		block:"P",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 288,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 116,
        Symbol: "Lv",
		name:"livermorium",
		type:"undefined",
		block:"P",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 293,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 117,
        Symbol: "Ts",
		name:"Tennessine",
		type:"undefined",
		block:"P",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 294,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    }, {
        proton: 118,
        Symbol: "Og",
		name:"Oganesson",
		type:"undefined",
		block:"P",
        boilingPoint: null,
        Electronegativity: null,
        Density: null,
        AtomicMass: 294,
        IonizationEnergy: null,
        AtomicRadius: null,
		AtomicRadius_InPicometers: "N/A",
        MeltingPoint: null,
        ElementColor: "rgb(204,204,204)"
    },
];

PeriodicTable.getElementById = function(id)
{
    for (var i = 0; i < PeriodicTable.length; i++)
	{
        var temp = PeriodicTable[i];
        if (temp.proton == id)
            return temp;
    }
    return false;
}

PeriodicTable.getElementByName = function(name)
{
    for (var i = 0; i < PeriodicTable.length; i++)
	{
        var temp = PeriodicTable[i];
        if (temp.Symbol == name)
            return temp;
    }
    return false;
}

PeriodicTable.findByName = function(name)
{
    for (var i = 0; i < PeriodicTable.length; i++)
	{
        var temp = PeriodicTable[i];
        if (temp.name == name)
            return temp;
    }
    return false;
}

PeriodicTable.getNeutrons = function(name,iso)
{
	var obj = new Object();
	for (var i = 0; i < PeriodicTable.length; i++)
	{
		var temp = PeriodicTable[i];
		if (temp.name == name)
		{
			obj = temp;
			break;
		}
	}
	if(obj.isotope.indexOf(iso) == -1)
	{
		return "Invalid isotope";
	}
	else
	{
		var n = iso*1 - obj.proton;
		return n;
	}
}
